# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ad1e6d0ef0e5204aa19b95cf08144cb272bad02bb9978cd73fd0af81955f4118b24f8db433929b6a56efaccf0c80093dd81bf301565389ba1414fa70312f533

test:
  secret_key_base: df446e12835191a9cc61183972cdb417f6cc61ff43f0d4c9de9a814331f4a372d991a54b5da6d22284da3557a916be002cd04bf27df5ca0f2e8b1cd52522f71b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
